### ISSUE TITLE
Got json unmarshal error with simple query

### ISSUE THREAD

**Issue by keyolk** [turbot/steampipe-plugin-sentry#5]
**Describe the bug**
```
select
  name,
  project_slug
from
  sentry_metric_alert
where
  project_slug = 'test';

Error: json: cannot unmarshal number into Go struct field MetricAlertTriggerAction.triggers.actions.targetIdentifier of type string (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
```
$ steampipe --version
Steampipe v0.20.10
```

**Plugin version (`steampipe plugin list`)**
```
$ steampipe plugin list
+--------------------------------------------------+---------+----------------------------------+
| Installed Plugin                                 | Version | Connections                      |
+--------------------------------------------------+---------+----------------------------------+
| hub.steampipe.io/plugins/turbot/sentry@latest    | 0.0.1   | sentry                           |
+--------------------------------------------------+---------+----------------------------------+
```

**Comment by misraved** [comment]
Apologies for the snag @keyolk and thanks for pointing it out 👍.

I tried to reproduce the error without much success. I was able to query the table successfully - 

```
 select
  name,
  project_slug, triggers
from
  sentry_metric_alert
where
  project_slug = 'go';
[
 {
  "name": "Send a notification for new issues copy",
  "project_slug": "go",
  "triggers": [
   {
    "actions": [
     {
      "alertRuleTriggerId": "285111",
      "dateCreated": "2023-09-04T12:10:22.317899Z",
      "desc": "Send a notification to test@gmail.com",
      "id": "273156",
      "targetIdentifier": "2869123",
      "targetType": "user",
      "type": "email"
     }
    ],
    "alertRuleId": "171098",
    "alertThreshold": 10,
    "dateCreated": "2023-09-04T12:10:22.311211Z",
    "id": "285855",
    "label": "critical",
    "thresholdType": 0
   }
  ]
 }
]

Could you please mention the number of alerts that you have for this project slug? I suspect this could be a result of a bad metric filter.

**Comment by keyolk** [comment]
25 alert rules from `/0/organizations/${org}/alert-rules//"`
One of them has no actions in one of its triggers.

**Comment by misraved** [comment]
Thanks @keyolk, that's helpful!!

**Comment by graza-io** [comment]
@keyolk - for this table it uses the API call `0/projects/${orgSlug}/${projectSlug}/alert-rules/`

If you then look through the response objects do any of them contain a non-string value under the `triggers.actions.targetIdentifier` (may look like the existing other string identifiers o.e. just numbers, but not wrapped in quotes) if so can you relay some additional information to us such as the `triggers.actions.targetType` and how many instances of this situation you come across?

Thanks in advance!

**Comment by graza-io** [comment]
Hey @keyolk - have you had a chance to test the above? 

Would be useful to have confirmation on my assumptions so that an issue can be raised to the SDK repo for a fix :)

**Comment by keyolk** [comment]
@graza-io 
Well, in my case there are no numeric values in `targetIdentifier`.
Also all its `targetType` is `specific`

I can see an alert rule with empty actions. 
it looks like
```json
[
 {
    "id": "255884",
    "alertRuleId": "152424",
    "label": "critical",
    "thresholdType": 0,
    "alertThreshold": 10,
    "resolveThreshold": 0,
    "dateCreated": "2023-06-13T02:30:46.271205Z",
    "actions": []
  },
...
```
Others, all its `targetIdentifier` has quoted string values.

**Comment by keyolk** [comment]
Now found what cause this.
I don't know well about sentry's API but
But seems this plugin sends requests like

```
/alert-rules/?cursor=25%3A1%3A0"
```

with the above queryparam, 
one of its returned items contains the numeric value to `targetIdentifier`
It might be their server or SDK problem : (

```json
{
    "id": "89074",
...
    "status": 0,
    "queryType": 0,
    "dataset": "events",
    "query": "",
    "aggregate": "count()",
    "thresholdType": 0,
    "resolveThreshold": null,
    "timeWindow": 5,
    "environment": null,
    "resolution": 1,
    "thresholdPeriod": 1,
    "triggers": [
      {
        "id": "153367",
        "alertRuleId": "89074",
        "label": "critical",
        "thresholdType": 0,
        "alertThreshold": 10000,
        "resolveThreshold": null,
        "dateCreated": "2022-09-27T09:03:21.101596Z",
        "actions": [
          {
            "id": "143676",
            "alertRuleTriggerId": "153367",
            "type": "pagerduty",
            "targetType": "specific",
            "targetIdentifier": 8705,
...
          }
        ]
      }
    ],
```

**Comment by graza-io** [comment]
This issue was supposedly fixed in upstream library; will need to update our reference and hopefully that will resolve this issue.
